# Generated by Django 6.0 on 2025-12-28 09:24

import apps.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
            bases=(apps.core.mixins.AutoSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('release_year', models.PositiveIntegerField(verbose_name='Release year')),
                ('poster', models.ImageField(upload_to='movies/posters', verbose_name='Poster')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration (minutes)')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-release_year'],
            },
            bases=(apps.core.mixins.AutoSlugMixin, models.Model),
        ),
    ]
