# Generated by Django 6.0 on 2025-12-28 12:02

import apps.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/', verbose_name='Photo')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of birthday')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
            bases=(apps.core.mixins.AutoSlugMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='actors_movies', to='movies.person', verbose_name='Актеры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='directed_movies', to='movies.person', verbose_name='Режиссеры'),
        ),
    ]
