# Generated by Django 6.0 on 2025-12-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_person_alter_movie_description_movie_actors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_year'], 'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
        migrations.AddField(
            model_name='movie',
            name='seasons_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество сезонов'),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал')], default='movie', max_length=10, verbose_name='Тип'),
        ),
    ]
