# Generated by Django 6.0 on 2026-01-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_options_movie_seasons_count_movie_type'),
        ('reviews', '0002_review_title_alter_review_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Content',
        ),
    ]
