# Generated by Django 6.0 on 2026-01-09 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Без названия', max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(15000)], verbose_name='Текст отзыва'),
        ),
    ]
